### ISSUE TITLE
Releases & APKs gone?

### ISSUE THREAD

**Issue by IzzySoft** [Yash-Garg/KeyManager#3]
Looks like releases and APKs have disappeared. Would you please add them back? Some Android users have no access to PlayStore and thus are currently left out :wink: Thanks!

**Comment by yash-garg** [comment]
EDIT: Added!

https://github.com/Yash-Garg/KeyManager/releases/tag/v1.1

**Comment by IzzySoft** [comment]
That was fast – thanks a lot! Update will [show up here](https://apt.izzysoft.de/fdroid/index/apk/dev.yash.keymanager) with the next sync in less than 18h. Any [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) can be used to keep it updated on-device, no account needed :smiley: Updates are picked up automatically from your repo here within 24h after you make the APK available at a new tag. Be welcome to add [these badges](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to point there if you like.

**Comment by yash-garg** [comment]
> That was fast – thanks a lot! Update will [show up here](https://apt.izzysoft.de/fdroid/index/apk/dev.yash.keymanager) with the next sync in less than 18h. Any [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) can be used to keep it updated on-device, no account needed 😃 Updates are picked up automatically from your repo here within 24h after you make the APK available at a new tag. Be welcome to add [these badges](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to point there if you like.

Great! I'll check and see if I can automate builds directly to Fdroid.

**Comment by IzzySoft** [comment]
> Great!

Glad you like it – and thanks for adding the badge!

> I'll check and see if I can automate builds directly to Fdroid.

That's already done for my repo (my updater automatically picks up your new releases within 24h, as described). My repo can be used with any F-Droid client. But if you want your app directly listed with [F-Droid.org](https://f-droid.org/), that probably could be done as well – though then F-Droid would build the APKs from your tags and sign them with their own app-specific key. If you're interested in that, you can [request packaging](https://gitlab.com/fdroid/rfp/issues) – ah, I see [you already did](https://gitlab.com/fdroid/rfp/-/issues/1912), congrats! Inclusion criteria there are a bit stricter than with my repo, though :wink: Best luck, and we'll probably meet "over there" again (disclosure: I'm one of the F-Droid maintainers).

**Comment by yash-garg** [comment]
> > Great!
> 
> Glad you like it – and thanks for adding the badge!
> 
> > I'll check and see if I can automate builds directly to Fdroid.
> 
> That's already done for my repo (my updater automatically picks up your new releases within 24h, as described). My repo can be used with any F-Droid client. But if you want your app directly listed with [F-Droid.org](https://f-droid.org/), that probably could be done as well – though then F-Droid would build the APKs from your tags and sign them with their own app-specific key. If you're interested in that, you can [request packaging](https://gitlab.com/fdroid/rfp/issues) – ah, I see [you already did](https://gitlab.com/fdroid/rfp/-/issues/1912), congrats! Inclusion criteria there are a bit stricter than with my repo, though 😉 Best luck, and we'll probably meet "over there" again (disclosure: I'm one of the F-Droid maintainers).

Yep I saw you are one of the maintainers. Pleasure meeting! Will look into FDroid stuff seemed a bit tricky, for now will just add your repo in FDroid app.

**Comment by IzzySoft** [comment]
Fine with me :green_heart: If you want to know what F-Droid's scanner has to report, you'd just have to leave that RFP open until it reported (takes less than a day, and might give some interesting hints).
